### ISSUE TITLE
Problems bot

### ISSUE THREAD

**Issue by derecklefou** [glephraug/satisfactory-discord-bot#1]
Hello, I have some problems to make the bot work properly would you help me

**Comment by glephraug** [comment]
Can you describe what you're trying to do and what issues you're facing?

**Comment by derecklefou** [comment]
![instance](https://user-images.githubusercontent.com/74102669/147118689-4496a625-3761-4e7a-952e-ac748f33ef14.PNG)
![id](https://user-images.githubusercontent.com/74102669/147118789-cd7999e6-7c7c-4509-8b5a-feebd4d5cdd3.PNG)
I have this error that runs when I make the command to display instance

**Comment by glephraug** [comment]
You need a value for AWS_REGION in your .env file. Depending on the permissions of the AWS instance you're connecting to you may also need a value for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.

**Comment by derecklefou** [comment]
How I also have this information after typing the commands in the .env

**Comment by derecklefou** [comment]
What information should be inserted after the =

**Comment by glephraug** [comment]
The bot is meant to be used with an EC2 instance you control. AWS_REGION would be the region your instance is in, such as us-east-2. The access keys are obtained through AWS when you set up permissions through IAM.

**Comment by derecklefou** [comment]
on a dedicated server we find it's info or precisely

**Comment by derecklefou** [comment]
on a dedicated server we find it's info or precisely

**Comment by derecklefou** [comment]
![ids](https://user-images.githubusercontent.com/74102669/147144798-1ab6e55b-7c10-4b03-ac7a-8827d9b8ccda.PNG)

**Comment by glephraug** [comment]
Is your Satisfactory dedicated server running on an Amazon EC2 instance? If so, you can find your instance's region through the AWS interface. If not, I don't think the bot will work.
